version: 0.2

phases:
  build:
    commands:
      - echo "Listing repo contents"
      - ls -l
      - echo "Listing script folder"
      - ls -l script/
      - echo "Uploading Glue script to S3"
      - aws s3 cp script/ s3://akhil-iceberg/swati-glue-scripts-ap-south-1/script/ --recursive
      - echo "Updating Glue transformation job: script"
      - aws glue update-job --job-name script --job-update Command="{Name=glueetl,ScriptLocation=s3://akhil-iceberg/swati-glue-scripts-ap-south-1/script/script.py}"
