version: 0.2

phases:
  build:
    commands:
      - echo "Uploading Glue script to S3"
      - aws s3 cp script/ s3://akhil-iceberg/swati-glue-scripts-ap-south-1/script/ --recursive

      - echo "Updating Glue transformation job:script"
      - |
        aws glue update-job \
          --job-name script \
          --job-update '{
            "Role":"arn:aws:iam::746252170258:role/Iam_glue",
            "Command": {
              "Name":"glueetl",
              "ScriptLocation":"s3://akhil-iceberg/swati-glue-scripts-ap-south-1/script/script.py"
            }
          }'
